export const GameActions = {
    START_GAME: 'START_GAME',
    SET_RICK_RANDOM_OPTIONS: 'SET_RICK_RANDOM_OPTIONS',
    SET_CORRECT_RICK: 'SET_CORRECT_RICK',
    CHECK_CORRECT_RICK: 'CHECK_CORRECT_RICK',
    INCREMENT_POINTS: 'INCREMENT_POINTS',
    SET_GAME_OVER: 'SET_GAME_OVER',
}