export const GameActions = {
    START_GAME: 'START_GAME',
    SET_CHARACTER_RANDOM_OPTIONS: 'SET_CHARACTER_RANDOM_OPTIONS',
    SET_CORRECT_CHARACTER: 'SET_CORRECT_CHARACTER',
    CHECK_CORRECT_CHARACTER: 'CHECK_CORRECT_CHARACTER',
    INCREMENT_POINTS: 'INCREMENT_POINTS',
    SET_GAME_OVER: 'SET_GAME_OVER',
}