export const GameActions = {
    SET_LOADING: 'SET_LOADING',
    GET_ALL_CHARACTERS: 'GET_ALL_CHARACTERS',
    SET_CHARACTER_RANDOM_OPTIONS: 'SET_CHARACTER_RANDOM_OPTIONS',
    START_GAME: 'START_GAME',
    SET_CORRECT_CHARACTER: 'SET_CORRECT_CHARACTER',
    CHECK_CORRECT_CHARACTER: 'CHECK_CORRECT_CHARACTER',
    INCREMENT_POINTS: 'INCREMENT_POINTS',
    REMOVE_SELECTED_CHARACTER_FROM_UNSELECTED_CHARACTERS: 'REMOVE_SELECTED_CHARACTER_FROM_UNSELECTED_CHARACTERS',
    RESET_UNSELECTED_CHARACTERS: 'RESET_SELECTED_CHARACTERS',
    SET_GAME_OVER: 'SET_GAME_OVER',
    SET_WIN: 'SET_WIN',
}